services:
  backend:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
  frontend:
    build: ./ui
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/ui
      - nodemodules:/src/node_modules
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"

volumes:
  nodemodules: {}